//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Mockifier.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Mockifier.Parser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;CustomProps&amp;gt;&amp;lt;OrderedProcessing vt=&quot;11&quot;&amp;gt;0&amp;lt;/OrderedProcessing&amp;gt;&amp;lt;InboundBodyLocation vt=&quot;8&quot;&amp;gt;UseBodyPath&amp;lt;/InboundBodyLocation&amp;gt;&amp;lt;InboundBodyPathExpression vt=&quot;8&quot;&amp;gt;/MessageContent&amp;lt;/InboundBodyPathExpression&amp;gt;&amp;lt;OutboundBodyLocation vt=&quot;8&quot;&amp;gt;UseBodyElement&amp;lt;/OutboundBodyLocation&amp;gt;&amp;lt;AffiliateApplicationName vt=&quot;8&quot; /&amp;gt;&amp;lt;BindingType vt=&quot;8&quot;&amp;gt;mockBinding&amp;lt;/BindingType&amp;gt;&amp;lt;DisableLocationOnFailure vt=&quot;11&quot;&amp;gt;0&amp;lt;/DisableLocationOnFailure&amp;gt;&amp;lt;UserName vt=&quot;8&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2010_ReceiveLocationOneWay {
            get {
                return ResourceManager.GetString("BTS2010_ReceiveLocationOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;CustomProps&amp;gt;&amp;lt;OrderedProcessing vt=&quot;11&quot;&amp;gt;0&amp;lt;/OrderedProcessing&amp;gt;&amp;lt;InboundBodyLocation vt=&quot;8&quot;&amp;gt;UseBodyPath&amp;lt;/InboundBodyLocation&amp;gt;&amp;lt;InboundBodyPathExpression vt=&quot;8&quot;&amp;gt;/MessageContent&amp;lt;/InboundBodyPathExpression&amp;gt;&amp;lt;OutboundBodyLocation vt=&quot;8&quot;&amp;gt;UseTemplate&amp;lt;/OutboundBodyLocation&amp;gt;&amp;lt;AffiliateApplicationName vt=&quot;8&quot; /&amp;gt;&amp;lt;BindingType vt=&quot;8&quot;&amp;gt;mockBinding&amp;lt;/BindingType&amp;gt;&amp;lt;DisableLocationOnFailure vt=&quot;11&quot;&amp;gt;0&amp;lt;/DisableLocationOnFailure&amp;gt;&amp;lt;UserName vt=&quot;8&quot; /&amp;gt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2010_ReceiveLocationTwoWays {
            get {
                return ResourceManager.GetString("BTS2010_ReceiveLocationTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;CustomProps&amp;gt;&amp;lt;BindingConfiguration vt=&quot;8&quot;&amp;gt;&amp;amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;amp;gt;&amp;lt;/BindingConfiguration&amp;gt;&amp;lt;InboundBodyPathExpression vt=&quot;8&quot; /&amp;gt;&amp;lt;OutboundBodyLocation vt=&quot;8&quot;&amp;gt;UseTemplate&amp;lt;/OutboundBodyLocation&amp;gt;&amp;lt;AffiliateApplicationName vt=&quot;8&quot; /&amp;gt;&amp;lt;EnableTransaction vt=&quot;11&quot;&amp;gt;0&amp;lt;/EnableTransaction&amp;gt;&amp;lt;StaticAction vt=&quot;8&quot; /&amp;gt;&amp;lt;BindingType vt=&quot;8&quot;&amp;gt;mockBinding&amp;lt;/BindingType&amp;gt;&amp;lt;ProxyAddress vt=&quot;8&quot; /&amp;gt;&amp;lt;UserName vt=&quot;8&quot; /&amp;gt;&amp;lt;I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2010_SendPortOneWay {
            get {
                return ResourceManager.GetString("BTS2010_SendPortOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;CustomProps&amp;gt;&amp;lt;BindingConfiguration vt=&quot;8&quot;&amp;gt;&amp;amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;amp;gt;&amp;lt;/BindingConfiguration&amp;gt;&amp;lt;InboundBodyPathExpression vt=&quot;8&quot;&amp;gt;/MessageContent&amp;lt;/InboundBodyPathExpression&amp;gt;&amp;lt;OutboundBodyLocation vt=&quot;8&quot;&amp;gt;UseTemplate&amp;lt;/OutboundBodyLocation&amp;gt;&amp;lt;AffiliateApplicationName vt=&quot;8&quot; /&amp;gt;&amp;lt;EnableTransaction vt=&quot;11&quot;&amp;gt;0&amp;lt;/EnableTransaction&amp;gt;&amp;lt;StaticAction vt=&quot;8&quot; /&amp;gt;&amp;lt;BindingType vt=&quot;8&quot;&amp;gt;mockBinding&amp;lt;/BindingType&amp;gt;&amp;lt;ProxyAdd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2010_SendPortTwoWays {
            get {
                return ResourceManager.GetString("BTS2010_SendPortTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;CustomProps&amp;gt;&amp;lt;BindingConfiguration vt=&quot;8&quot;&amp;gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; PromotedProperties=&quot;{PromotedProperties}&quot; /&amp;gt;&amp;lt;/BindingConfiguration&amp;gt;&amp;lt;InboundBodyPathExpression vt=&quot;8&quot;&amp;gt;/MessageContent&amp;lt;/InboundBodyPathExpression&amp;gt;&amp;lt;InboundBodyLocation vt=&quot;8&quot;&amp;gt;UseBodyPath&amp;lt;/InboundBodyLocation&amp;gt;&amp;lt;AffiliateApplicationName vt=&quot;8&quot; /&amp;gt;&amp;lt;BindingType vt=&quot;8&quot;&amp;gt;mockBinding&amp;lt;/BindingType&amp;gt;&amp;lt;DisableLocationOnFailure vt=&quot;11&quot;&amp;gt;0&amp;lt;/DisableLocationOnFailur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2013_ReceiveLocationOneWay {
            get {
                return ResourceManager.GetString("BTS2013_ReceiveLocationOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;CustomProps&amp;gt;&amp;lt;BindingConfiguration vt=&quot;8&quot;&amp;gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; PromotedProperties=&quot;{PromotedProperties}&quot; /&amp;gt;&amp;lt;/BindingConfiguration&amp;gt;&amp;lt;InboundBodyPathExpression vt=&quot;8&quot;&amp;gt;/MessageContent&amp;lt;/InboundBodyPathExpression&amp;gt;&amp;lt;InboundBodyLocation vt=&quot;8&quot;&amp;gt;UseBodyPath&amp;lt;/InboundBodyLocation&amp;gt;&amp;lt;AffiliateApplicationName vt=&quot;8&quot; /&amp;gt;&amp;lt;BindingType vt=&quot;8&quot;&amp;gt;mockBinding&amp;lt;/BindingType&amp;gt;&amp;lt;DisableLocationOnFailure vt=&quot;11&quot;&amp;gt;0&amp;lt;/DisableLocationOnFailur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2013_ReceiveLocationTwoWays {
            get {
                return ResourceManager.GetString("BTS2013_ReceiveLocationTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;CustomProps&amp;gt;&amp;lt;BindingType vt=&quot;8&quot;&amp;gt;mockBinding&amp;lt;/BindingType&amp;gt;&amp;lt;BindingConfiguration vt=&quot;8&quot;&amp;gt;&amp;amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;amp;gt;&amp;lt;/BindingConfiguration&amp;gt;&amp;lt;InboundBodyPathExpression vt=&quot;8&quot; /&amp;gt;&amp;lt;OutboundBodyLocation vt=&quot;8&quot;&amp;gt;UseTemplate&amp;lt;/OutboundBodyLocation&amp;gt;&amp;lt;AffiliateApplicationName vt=&quot;8&quot; /&amp;gt;&amp;lt;StaticAction vt=&quot;8&quot; /&amp;gt;&amp;lt;ProxyUserName vt=&quot;8&quot; /&amp;gt;&amp;lt;ProxyAddress vt=&quot;8&quot; /&amp;gt;&amp;lt;UserName vt=&quot;8&quot; /&amp;gt;&amp;lt;InboundBodyLocation vt=&quot;8&quot;&amp;gt;U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2013_SendPortOneWay {
            get {
                return ResourceManager.GetString("BTS2013_SendPortOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;CustomProps&amp;gt;&amp;lt;BindingType vt=&quot;8&quot;&amp;gt;mockBinding&amp;lt;/BindingType&amp;gt;&amp;lt;BindingConfiguration vt=&quot;8&quot;&amp;gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;gt;&amp;lt;/BindingConfiguration&amp;gt;&amp;lt;InboundBodyPathExpression vt=&quot;8&quot;&amp;gt;/MessageContent&amp;lt;/InboundBodyPathExpression&amp;gt;&amp;lt;OutboundBodyLocation vt=&quot;8&quot;&amp;gt;UseTemplate&amp;lt;/OutboundBodyLocation&amp;gt;&amp;lt;AffiliateApplicationName vt=&quot;8&quot; /&amp;gt;&amp;lt;StaticAction vt=&quot;8&quot; /&amp;gt;&amp;lt;ProxyUserName vt=&quot;8&quot; /&amp;gt;&amp;lt;ProxyAddress vt=&quot;8&quot; /&amp;gt;&amp;lt;UserName vt=&quot;8&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2013_SendPortTwoWays {
            get {
                return ResourceManager.GetString("BTS2013_SendPortTwoWays", resourceCulture);
            }
        }
    }
}
