//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Mockifier.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Mockifier.Parser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;OrderedProcessing vt=&quot;11&quot;&gt;0&lt;/OrderedProcessing&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLocation&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;OutboundBodyLocation vt=&quot;8&quot;&gt;UseBodyElement&lt;/OutboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;DisableLocationOnFailure vt=&quot;11&quot;&gt;0&lt;/DisableLocationOnFailure&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;ServiceBehaviorConfiguration vt=&quot;8&quot;&gt;{ServiceBehavior}&lt;/ServiceBehaviorConfiguration&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2010_ReceiveLocationOneWay {
            get {
                return ResourceManager.GetString("BTS2010_ReceiveLocationOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;OrderedProcessing vt=&quot;11&quot;&gt;0&lt;/OrderedProcessing&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLocation&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;OutboundBodyLocation vt=&quot;8&quot;&gt;UseTemplate&lt;/OutboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;DisableLocationOnFailure vt=&quot;11&quot;&gt;0&lt;/DisableLocationOnFailure&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;ServiceBehaviorConfiguration vt=&quot;8&quot;&gt;{ServiceBehavior}&lt;/ServiceBehaviorConfiguration&gt;&lt;End [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2010_ReceiveLocationTwoWays {
            get {
                return ResourceManager.GetString("BTS2010_ReceiveLocationTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot; /&gt;&lt;OutboundBodyLocation vt=&quot;8&quot;&gt;UseTemplate&lt;/OutboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;EnableTransaction vt=&quot;11&quot;&gt;0&lt;/EnableTransaction&gt;&lt;StaticAction vt=&quot;8&quot; /&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;ProxyAddress vt=&quot;8&quot; /&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyElement&lt;/InboundBodyLocation&gt;&lt;EndpointBehaviorConfiguration vt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2010_SendPortOneWay {
            get {
                return ResourceManager.GetString("BTS2010_SendPortOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;OutboundBodyLocation vt=&quot;8&quot;&gt;UseTemplate&lt;/OutboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;EnableTransaction vt=&quot;11&quot;&gt;0&lt;/EnableTransaction&gt;&lt;StaticAction vt=&quot;8&quot; /&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;ProxyAddress vt=&quot;8&quot; /&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLoca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2010_SendPortTwoWays {
            get {
                return ResourceManager.GetString("BTS2010_SendPortTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; PromotedProperties=&quot;{PromotedProperties}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;DisableLocationOnFailure vt=&quot;11&quot;&gt;0&lt;/DisableLocationOnFailure&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;ServiceBehaviorConfiguration vt=&quot;8&quot;&gt;{ServiceBeh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2013_ReceiveLocationOneWay {
            get {
                return ResourceManager.GetString("BTS2013_ReceiveLocationOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; PromotedProperties=&quot;{PromotedProperties}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;DisableLocationOnFailure vt=&quot;11&quot;&gt;0&lt;/DisableLocationOnFailure&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;ServiceBehaviorConfiguration vt=&quot;8&quot;&gt;{ServiceBeh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2013_ReceiveLocationTwoWays {
            get {
                return ResourceManager.GetString("BTS2013_ReceiveLocationTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot; /&gt;&lt;OutboundBodyLocation vt=&quot;8&quot;&gt;UseTemplate&lt;/OutboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;StaticAction vt=&quot;8&quot; /&gt;&lt;ProxyUserName vt=&quot;8&quot; /&gt;&lt;ProxyAddress vt=&quot;8&quot; /&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyElement&lt;/InboundBodyLocation&gt;&lt;EndpointBehaviorConfiguration vt=&quot;8&quot;&gt;{EndpointBehavior}&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2013_SendPortOneWay {
            get {
                return ResourceManager.GetString("BTS2013_SendPortOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;OutboundBodyLocation vt=&quot;8&quot;&gt;UseTemplate&lt;/OutboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;StaticAction vt=&quot;8&quot; /&gt;&lt;ProxyUserName vt=&quot;8&quot; /&gt;&lt;ProxyAddress vt=&quot;8&quot; /&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLocation&gt;&lt;EndpointBehaviorCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2013_SendPortTwoWays {
            get {
                return ResourceManager.GetString("BTS2013_SendPortTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; PromotedProperties=&quot;{PromotedProperties}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;DisableLocationOnFailure vt=&quot;11&quot;&gt;0&lt;/DisableLocationOnFailure&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;ServiceBehaviorConfiguration vt=&quot;8&quot;&gt;{ServiceBeh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2016_ReceiveLocationOneWay {
            get {
                return ResourceManager.GetString("BTS2016_ReceiveLocationOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; PromotedProperties=&quot;{PromotedProperties}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;DisableLocationOnFailure vt=&quot;11&quot;&gt;0&lt;/DisableLocationOnFailure&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;ServiceBehaviorConfiguration vt=&quot;8&quot;&gt;{ServiceBeh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2016_ReceiveLocationTwoWays {
            get {
                return ResourceManager.GetString("BTS2016_ReceiveLocationTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot; /&gt;&lt;OutboundBodyLocation vt=&quot;8&quot;&gt;UseTemplate&lt;/OutboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;StaticAction vt=&quot;8&quot; /&gt;&lt;ProxyUserName vt=&quot;8&quot; /&gt;&lt;ProxyAddress vt=&quot;8&quot; /&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyElement&lt;/InboundBodyLocation&gt;&lt;EndpointBehaviorConfiguration vt=&quot;8&quot;&gt;{EndpointBehavior}&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2016_SendPortOneWay {
            get {
                return ResourceManager.GetString("BTS2016_SendPortOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CustomProps&gt;&lt;BindingType vt=&quot;8&quot;&gt;mockBinding&lt;/BindingType&gt;&lt;BindingConfiguration vt=&quot;8&quot;&gt;&amp;lt;binding name=&quot;mockBinding&quot; Encoding=&quot;{Encoding}&quot; /&amp;gt;&lt;/BindingConfiguration&gt;&lt;InboundBodyPathExpression vt=&quot;8&quot;&gt;/MessageContent&lt;/InboundBodyPathExpression&gt;&lt;OutboundBodyLocation vt=&quot;8&quot;&gt;UseTemplate&lt;/OutboundBodyLocation&gt;&lt;AffiliateApplicationName vt=&quot;8&quot; /&gt;&lt;StaticAction vt=&quot;8&quot; /&gt;&lt;ProxyUserName vt=&quot;8&quot; /&gt;&lt;ProxyAddress vt=&quot;8&quot; /&gt;&lt;UserName vt=&quot;8&quot; /&gt;&lt;InboundBodyLocation vt=&quot;8&quot;&gt;UseBodyPath&lt;/InboundBodyLocation&gt;&lt;EndpointBehaviorCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTS2016_SendPortTwoWays {
            get {
                return ResourceManager.GetString("BTS2016_SendPortTwoWays", resourceCulture);
            }
        }
    }
}
