//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BTS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BTS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.BTS", typeof(BTS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckDescription.
        /// </summary>
        public static string AckDescription {
            get {
                return ResourceManager.GetString("AckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckFailureCategory.
        /// </summary>
        public static string AckFailureCategory {
            get {
                return ResourceManager.GetString("AckFailureCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckFailureCode.
        /// </summary>
        public static string AckFailureCode {
            get {
                return ResourceManager.GetString("AckFailureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckID.
        /// </summary>
        public static string AckID {
            get {
                return ResourceManager.GetString("AckID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckInboundTransportLocation.
        /// </summary>
        public static string AckInboundTransportLocation {
            get {
                return ResourceManager.GetString("AckInboundTransportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckOutboundTransportLocation.
        /// </summary>
        public static string AckOutboundTransportLocation {
            get {
                return ResourceManager.GetString("AckOutboundTransportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckOwnerID.
        /// </summary>
        public static string AckOwnerID {
            get {
                return ResourceManager.GetString("AckOwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckReceivePortID.
        /// </summary>
        public static string AckReceivePortID {
            get {
                return ResourceManager.GetString("AckReceivePortID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckReceivePortName.
        /// </summary>
        public static string AckReceivePortName {
            get {
                return ResourceManager.GetString("AckReceivePortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckRequired.
        /// </summary>
        public static string AckRequired {
            get {
                return ResourceManager.GetString("AckRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckSendPortID.
        /// </summary>
        public static string AckSendPortID {
            get {
                return ResourceManager.GetString("AckSendPortID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckSendPortName.
        /// </summary>
        public static string AckSendPortName {
            get {
                return ResourceManager.GetString("AckSendPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#AckType.
        /// </summary>
        public static string AckType {
            get {
                return ResourceManager.GetString("AckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ActionOnFailure.
        /// </summary>
        public static string ActionOnFailure {
            get {
                return ResourceManager.GetString("ActionOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ActivationServiceID.
        /// </summary>
        public static string ActivationServiceID {
            get {
                return ResourceManager.GetString("ActivationServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#BackupEndpointInfo.
        /// </summary>
        public static string BackupEndpointInfo {
            get {
                return ResourceManager.GetString("BackupEndpointInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#BatchRequired.
        /// </summary>
        public static string BatchRequired {
            get {
                return ResourceManager.GetString("BatchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#BizTalkControl.
        /// </summary>
        public static string BizTalkControl {
            get {
                return ResourceManager.GetString("BizTalkControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#commitmentRct_commitmentCode.
        /// </summary>
        public static string BTF2_commitmentRct_commitmentCode {
            get {
                return ResourceManager.GetString("BTF2_commitmentRct_commitmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#commitmentRct_decidedAt.
        /// </summary>
        public static string BTF2_commitmentRct_decidedAt {
            get {
                return ResourceManager.GetString("BTF2_commitmentRct_decidedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#commitmentRct_decision.
        /// </summary>
        public static string BTF2_commitmentRct_decision {
            get {
                return ResourceManager.GetString("BTF2_commitmentRct_decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#commitmentRct_identity.
        /// </summary>
        public static string BTF2_commitmentRct_identity {
            get {
                return ResourceManager.GetString("BTF2_commitmentRct_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#deliveryRct_identity.
        /// </summary>
        public static string BTF2_deliveryRct_identity {
            get {
                return ResourceManager.GetString("BTF2_deliveryRct_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#deliveryRct_receivedAt.
        /// </summary>
        public static string BTF2_deliveryRct_receivedAt {
            get {
                return ResourceManager.GetString("BTF2_deliveryRct_receivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#eps_from_address.
        /// </summary>
        public static string BTF2_eps_from_address {
            get {
                return ResourceManager.GetString("BTF2_eps_from_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#eps_from_address_type.
        /// </summary>
        public static string BTF2_eps_from_address_type {
            get {
                return ResourceManager.GetString("BTF2_eps_from_address_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#eps_to_address.
        /// </summary>
        public static string BTF2_eps_to_address {
            get {
                return ResourceManager.GetString("BTF2_eps_to_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#eps_to_address_type.
        /// </summary>
        public static string BTF2_eps_to_address_type {
            get {
                return ResourceManager.GetString("BTF2_eps_to_address_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#fault_faultactor.
        /// </summary>
        public static string BTF2_fault_faultactor {
            get {
                return ResourceManager.GetString("BTF2_fault_faultactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#fault_faultcode.
        /// </summary>
        public static string BTF2_fault_faultcode {
            get {
                return ResourceManager.GetString("BTF2_fault_faultcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#fault_faultstring.
        /// </summary>
        public static string BTF2_fault_faultstring {
            get {
                return ResourceManager.GetString("BTF2_fault_faultstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#IsReliable.
        /// </summary>
        public static string BTF2_IsReliable {
            get {
                return ResourceManager.GetString("BTF2_IsReliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#PassAckThrough.
        /// </summary>
        public static string BTF2_PassAckThrough {
            get {
                return ResourceManager.GetString("BTF2_PassAckThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#prc_instance.
        /// </summary>
        public static string BTF2_prc_instance {
            get {
                return ResourceManager.GetString("BTF2_prc_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#prc_type.
        /// </summary>
        public static string BTF2_prc_type {
            get {
                return ResourceManager.GetString("BTF2_prc_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#prop_identity.
        /// </summary>
        public static string BTF2_prop_identity {
            get {
                return ResourceManager.GetString("BTF2_prop_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#prop_sentAt.
        /// </summary>
        public static string BTF2_prop_sentAt {
            get {
                return ResourceManager.GetString("BTF2_prop_sentAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#prop_topic.
        /// </summary>
        public static string BTF2_prop_topic {
            get {
                return ResourceManager.GetString("BTF2_prop_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#svc_commitmentRctRqt_sendBy.
        /// </summary>
        public static string BTF2_svc_commitmentRctRqt_sendBy {
            get {
                return ResourceManager.GetString("BTF2_svc_commitmentRctRqt_sendBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#svc_commitmentRctRqt_sendTo_address.
        /// </summary>
        public static string BTF2_svc_commitmentRctRqt_sendTo_address {
            get {
                return ResourceManager.GetString("BTF2_svc_commitmentRctRqt_sendTo_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#svc_commitmentRctRqt_sendTo_address_type.
        /// </summary>
        public static string BTF2_svc_commitmentRctRqt_sendTo_address_type {
            get {
                return ResourceManager.GetString("BTF2_svc_commitmentRctRqt_sendTo_address_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#svc_deliveryRctRqt_sendBy.
        /// </summary>
        public static string BTF2_svc_deliveryRctRqt_sendBy {
            get {
                return ResourceManager.GetString("BTF2_svc_deliveryRctRqt_sendBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#svc_deliveryRctRqt_sendTo_address.
        /// </summary>
        public static string BTF2_svc_deliveryRctRqt_sendTo_address {
            get {
                return ResourceManager.GetString("BTF2_svc_deliveryRctRqt_sendTo_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/btf2-properties#svc_deliveryRctRqt_sendTo_address_type.
        /// </summary>
        public static string BTF2_svc_deliveryRctRqt_sendTo_address_type {
            get {
                return ResourceManager.GetString("BTF2_svc_deliveryRctRqt_sendTo_address_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#CorrelationToken.
        /// </summary>
        public static string CorrelationToken {
            get {
                return ResourceManager.GetString("CorrelationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#DecryptionCert.
        /// </summary>
        public static string DecryptionCert {
            get {
                return ResourceManager.GetString("DecryptionCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#DestinationParty.
        /// </summary>
        public static string DestinationParty {
            get {
                return ResourceManager.GetString("DestinationParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#DestinationPartyID.
        /// </summary>
        public static string DestinationPartyID {
            get {
                return ResourceManager.GetString("DestinationPartyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#DestinationPartyQualifier.
        /// </summary>
        public static string DestinationPartyQualifier {
            get {
                return ResourceManager.GetString("DestinationPartyQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#EncryptionCert.
        /// </summary>
        public static string EncryptionCert {
            get {
                return ResourceManager.GetString("EncryptionCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/endpoint-properties#TwoWayReceivePort.
        /// </summary>
        public static string ENDPOINT_TwoWayReceivePort {
            get {
                return ResourceManager.GetString("ENDPOINT_TwoWayReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#EndpointGroup.
        /// </summary>
        public static string EndpointGroup {
            get {
                return ResourceManager.GetString("EndpointGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#EpmRRCorrelationToken.
        /// </summary>
        public static string EpmRRCorrelationToken {
            get {
                return ResourceManager.GetString("EpmRRCorrelationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ExpirationTime.
        /// </summary>
        public static string ExpirationTime {
            get {
                return ResourceManager.GetString("ExpirationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#FaultName.
        /// </summary>
        public static string FaultName {
            get {
                return ResourceManager.GetString("FaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#FaultQueue.
        /// </summary>
        public static string FaultQueue {
            get {
                return ResourceManager.GetString("FaultQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#InboundTransportLocation.
        /// </summary>
        public static string InboundTransportLocation {
            get {
                return ResourceManager.GetString("InboundTransportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#InboundTransportType.
        /// </summary>
        public static string InboundTransportType {
            get {
                return ResourceManager.GetString("InboundTransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#InterchangeID.
        /// </summary>
        public static string InterchangeID {
            get {
                return ResourceManager.GetString("InterchangeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#InterchangeSequenceNumber.
        /// </summary>
        public static string InterchangeSequenceNumber {
            get {
                return ResourceManager.GetString("InterchangeSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#IsDynamicSend.
        /// </summary>
        public static string IsDynamicSend {
            get {
                return ResourceManager.GetString("IsDynamicSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#IsFragmented.
        /// </summary>
        public static string IsFragmented {
            get {
                return ResourceManager.GetString("IsFragmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#IsRequestResponse.
        /// </summary>
        public static string IsRequestResponse {
            get {
                return ResourceManager.GetString("IsRequestResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#IsSolicitResponse.
        /// </summary>
        public static string IsSolicitResponse {
            get {
                return ResourceManager.GetString("IsSolicitResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#JobID.
        /// </summary>
        public static string JobID {
            get {
                return ResourceManager.GetString("JobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#LastInterchangeMessage.
        /// </summary>
        public static string LastInterchangeMessage {
            get {
                return ResourceManager.GetString("LastInterchangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#LoopBack.
        /// </summary>
        public static string LoopBack {
            get {
                return ResourceManager.GetString("LoopBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#LRPMsgBodyTracking.
        /// </summary>
        public static string LRPMsgBodyTracking {
            get {
                return ResourceManager.GetString("LRPMsgBodyTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#LTPMsgBodyTracking.
        /// </summary>
        public static string LTPMsgBodyTracking {
            get {
                return ResourceManager.GetString("LTPMsgBodyTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#MessageDestination.
        /// </summary>
        public static string MessageDestination {
            get {
                return ResourceManager.GetString("MessageDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#MessageExchangePattern.
        /// </summary>
        public static string MessageExchangePattern {
            get {
                return ResourceManager.GetString("MessageExchangePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#MessageID.
        /// </summary>
        public static string MessageID {
            get {
                return ResourceManager.GetString("MessageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#MessageType.
        /// </summary>
        public static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#OutboundTransportCLSID.
        /// </summary>
        public static string OutboundTransportCLSID {
            get {
                return ResourceManager.GetString("OutboundTransportCLSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#OutboundTransportLocation.
        /// </summary>
        public static string OutboundTransportLocation {
            get {
                return ResourceManager.GetString("OutboundTransportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#OutboundTransportType.
        /// </summary>
        public static string OutboundTransportType {
            get {
                return ResourceManager.GetString("OutboundTransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#PartnerPort.
        /// </summary>
        public static string PartnerPort {
            get {
                return ResourceManager.GetString("PartnerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#PartnerService.
        /// </summary>
        public static string PartnerService {
            get {
                return ResourceManager.GetString("PartnerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#PassThrough.
        /// </summary>
        public static string PassThrough {
            get {
                return ResourceManager.GetString("PassThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#PipelinesExecuted.
        /// </summary>
        public static string PipelinesExecuted {
            get {
                return ResourceManager.GetString("PipelinesExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ProcessingParts.
        /// </summary>
        public static string ProcessingParts {
            get {
                return ResourceManager.GetString("ProcessingParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#PropertiesToUpdate.
        /// </summary>
        public static string PropertiesToUpdate {
            get {
                return ResourceManager.GetString("PropertiesToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ReceivePipelineConfig.
        /// </summary>
        public static string ReceivePipelineConfig {
            get {
                return ResourceManager.GetString("ReceivePipelineConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ReceivePipelineID.
        /// </summary>
        public static string ReceivePipelineID {
            get {
                return ResourceManager.GetString("ReceivePipelineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ReceivePipelineResponseConfig.
        /// </summary>
        public static string ReceivePipelineResponseConfig {
            get {
                return ResourceManager.GetString("ReceivePipelineResponseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ReceivePortID.
        /// </summary>
        public static string ReceivePortID {
            get {
                return ResourceManager.GetString("ReceivePortID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ReceivePortName.
        /// </summary>
        public static string ReceivePortName {
            get {
                return ResourceManager.GetString("ReceivePortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ReceivePortTransformHint.
        /// </summary>
        public static string ReceivePortTransformHint {
            get {
                return ResourceManager.GetString("ReceivePortTransformHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#ReqRespTransmitPipelineID.
        /// </summary>
        public static string ReqRespTransmitPipelineID {
            get {
                return ResourceManager.GetString("ReqRespTransmitPipelineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#RetryCount.
        /// </summary>
        public static string RetryCount {
            get {
                return ResourceManager.GetString("RetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#RetryInterval.
        /// </summary>
        public static string RetryInterval {
            get {
                return ResourceManager.GetString("RetryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#RouteDirectToTP.
        /// </summary>
        public static string RouteDirectToTP {
            get {
                return ResourceManager.GetString("RouteDirectToTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SchemaStrongName.
        /// </summary>
        public static string SchemaStrongName {
            get {
                return ResourceManager.GetString("SchemaStrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SendPipelineConfig.
        /// </summary>
        public static string SendPipelineConfig {
            get {
                return ResourceManager.GetString("SendPipelineConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SendPipelineResponseConfig.
        /// </summary>
        public static string SendPipelineResponseConfig {
            get {
                return ResourceManager.GetString("SendPipelineResponseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SendPortTransformHint.
        /// </summary>
        public static string SendPortTransformHint {
            get {
                return ResourceManager.GetString("SendPortTransformHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SignatureCertificate.
        /// </summary>
        public static string SignatureCertificate {
            get {
                return ResourceManager.GetString("SignatureCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SigningCert.
        /// </summary>
        public static string SigningCert {
            get {
                return ResourceManager.GetString("SigningCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SOAPAction.
        /// </summary>
        public static string SOAPAction {
            get {
                return ResourceManager.GetString("SOAPAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SourceParty.
        /// </summary>
        public static string SourceParty {
            get {
                return ResourceManager.GetString("SourceParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SourcePartyEvidence.
        /// </summary>
        public static string SourcePartyEvidence {
            get {
                return ResourceManager.GetString("SourcePartyEvidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SourcePartyEvidenceQualifier.
        /// </summary>
        public static string SourcePartyEvidenceQualifier {
            get {
                return ResourceManager.GetString("SourcePartyEvidenceQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SourcePartyID.
        /// </summary>
        public static string SourcePartyID {
            get {
                return ResourceManager.GetString("SourcePartyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SourcePartyQualifier.
        /// </summary>
        public static string SourcePartyQualifier {
            get {
                return ResourceManager.GetString("SourcePartyQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SPGroupID.
        /// </summary>
        public static string SPGroupID {
            get {
                return ResourceManager.GetString("SPGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SPID.
        /// </summary>
        public static string SPID {
            get {
                return ResourceManager.GetString("SPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SPName.
        /// </summary>
        public static string SPName {
            get {
                return ResourceManager.GetString("SPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SPTransportBackupID.
        /// </summary>
        public static string SPTransportBackupID {
            get {
                return ResourceManager.GetString("SPTransportBackupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SPTransportID.
        /// </summary>
        public static string SPTransportID {
            get {
                return ResourceManager.GetString("SPTransportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SSOTicket.
        /// </summary>
        public static string SSOTicket {
            get {
                return ResourceManager.GetString("SSOTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SuppressRoutingFailureDiagnosticInfo.
        /// </summary>
        public static string SuppressRoutingFailureDiagnosticInfo {
            get {
                return ResourceManager.GetString("SuppressRoutingFailureDiagnosticInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SuspendAsNonResumable.
        /// </summary>
        public static string SuspendAsNonResumable {
            get {
                return ResourceManager.GetString("SuspendAsNonResumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SuspendMessageOnMappingFailure.
        /// </summary>
        public static string SuspendMessageOnMappingFailure {
            get {
                return ResourceManager.GetString("SuspendMessageOnMappingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#SuspendMessageOnRoutingFailure.
        /// </summary>
        public static string SuspendMessageOnRoutingFailure {
            get {
                return ResourceManager.GetString("SuspendMessageOnRoutingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#TransmitPipelineID.
        /// </summary>
        public static string TransmitPipelineID {
            get {
                return ResourceManager.GetString("TransmitPipelineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#TransmitWorkID.
        /// </summary>
        public static string TransmitWorkID {
            get {
                return ResourceManager.GetString("TransmitWorkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#WindowsUser.
        /// </summary>
        public static string WindowsUser {
            get {
                return ResourceManager.GetString("WindowsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties#WorkID.
        /// </summary>
        public static string WorkID {
            get {
                return ResourceManager.GetString("WorkID", resourceCulture);
            }
        }
    }
}
