//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EDI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EDI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.EDI", typeof(EDI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#AgreementID.
        /// </summary>
        public static string AgreementID {
            get {
                return ResourceManager.GetString("AgreementID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#AgreementName.
        /// </summary>
        public static string AgreementName {
            get {
                return ResourceManager.GetString("AgreementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#AgreementNameForSend.
        /// </summary>
        public static string AgreementNameForSend {
            get {
                return ResourceManager.GetString("AgreementNameForSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#AgreementPartIDForSend.
        /// </summary>
        public static string AgreementPartIDForSend {
            get {
                return ResourceManager.GetString("AgreementPartIDForSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#AgreementPartIDOnReceive.
        /// </summary>
        public static string AgreementPartIDOnReceive {
            get {
                return ResourceManager.GetString("AgreementPartIDOnReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#AK901.
        /// </summary>
        public static string AK901 {
            get {
                return ResourceManager.GetString("AK901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#AttachmentId.
        /// </summary>
        public static string AttachmentId {
            get {
                return ResourceManager.GetString("AttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#BatchElementValidationFailure.
        /// </summary>
        public static string BatchElementValidationFailure {
            get {
                return ResourceManager.GetString("BatchElementValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#BatchEncodingType.
        /// </summary>
        public static string BatchEncodingType {
            get {
                return ResourceManager.GetString("BatchEncodingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#BatchId.
        /// </summary>
        public static string BatchId {
            get {
                return ResourceManager.GetString("BatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#BatchIds.
        /// </summary>
        public static string BatchIds {
            get {
                return ResourceManager.GetString("BatchIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#BatchingError.
        /// </summary>
        public static string BatchingError {
            get {
                return ResourceManager.GetString("BatchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#BatchName.
        /// </summary>
        public static string BatchName {
            get {
                return ResourceManager.GetString("BatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#CodePage.
        /// </summary>
        public static string CodePage {
            get {
                return ResourceManager.GetString("CodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#CONTRL_UCI4.
        /// </summary>
        public static string CONTRL_UCI4 {
            get {
                return ResourceManager.GetString("CONTRL_UCI4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ControlActionType.
        /// </summary>
        public static string ControlActionType {
            get {
                return ResourceManager.GetString("ControlActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#DestinationEncodingTypes.
        /// </summary>
        public static string DestinationEncodingTypes {
            get {
                return ResourceManager.GetString("DestinationEncodingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#DestinationParties.
        /// </summary>
        public static string DestinationParties {
            get {
                return ResourceManager.GetString("DestinationParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#DestinationPartyId.
        /// </summary>
        public static string DestinationPartyId {
            get {
                return ResourceManager.GetString("DestinationPartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#DestinationPartyName.
        /// </summary>
        public static string DestinationPartyName {
            get {
                return ResourceManager.GetString("DestinationPartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#DestinationPartyReceiverIdentifier.
        /// </summary>
        public static string DestinationPartyReceiverIdentifier {
            get {
                return ResourceManager.GetString("DestinationPartyReceiverIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#DestinationPartyReceiverQualifier.
        /// </summary>
        public static string DestinationPartyReceiverQualifier {
            get {
                return ResourceManager.GetString("DestinationPartyReceiverQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#DestinationPartySenderIdentifier.
        /// </summary>
        public static string DestinationPartySenderIdentifier {
            get {
                return ResourceManager.GetString("DestinationPartySenderIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#DestinationPartySenderQualifier.
        /// </summary>
        public static string DestinationPartySenderQualifier {
            get {
                return ResourceManager.GetString("DestinationPartySenderQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#EncodingType.
        /// </summary>
        public static string EncodingType {
            get {
                return ResourceManager.GetString("EncodingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ErrorDescription.
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#GE01.
        /// </summary>
        public static string GE01 {
            get {
                return ResourceManager.GetString("GE01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#GS_Segment.
        /// </summary>
        public static string GS_Segment {
            get {
                return ResourceManager.GetString("GS_Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#GS01.
        /// </summary>
        public static string GS01 {
            get {
                return ResourceManager.GetString("GS01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#GS02.
        /// </summary>
        public static string GS02 {
            get {
                return ResourceManager.GetString("GS02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#GS03.
        /// </summary>
        public static string GS03 {
            get {
                return ResourceManager.GetString("GS03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#GS07.
        /// </summary>
        public static string GS07 {
            get {
                return ResourceManager.GetString("GS07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#GS08.
        /// </summary>
        public static string GS08 {
            get {
                return ResourceManager.GetString("GS08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#IgnoreEncodingType.
        /// </summary>
        public static string IgnoreEncodingType {
            get {
                return ResourceManager.GetString("IgnoreEncodingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ISA_Segment.
        /// </summary>
        public static string ISA_Segment {
            get {
                return ResourceManager.GetString("ISA_Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ISA05.
        /// </summary>
        public static string ISA05 {
            get {
                return ResourceManager.GetString("ISA05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ISA06.
        /// </summary>
        public static string ISA06 {
            get {
                return ResourceManager.GetString("ISA06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ISA07.
        /// </summary>
        public static string ISA07 {
            get {
                return ResourceManager.GetString("ISA07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ISA08.
        /// </summary>
        public static string ISA08 {
            get {
                return ResourceManager.GetString("ISA08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ISA15.
        /// </summary>
        public static string ISA15 {
            get {
                return ResourceManager.GetString("ISA15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#IsResendControlMessage.
        /// </summary>
        public static string IsResendControlMessage {
            get {
                return ResourceManager.GetString("IsResendControlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#IsSystemGeneratedAck.
        /// </summary>
        public static string IsSystemGeneratedAck {
            get {
                return ResourceManager.GetString("IsSystemGeneratedAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#PopulateInterchangeValues.
        /// </summary>
        public static string PopulateInterchangeValues {
            get {
                return ResourceManager.GetString("PopulateInterchangeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ReceiverPartyName.
        /// </summary>
        public static string ReceiverPartyName {
            get {
                return ResourceManager.GetString("ReceiverPartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ReceiverPartyNameForSend.
        /// </summary>
        public static string ReceiverPartyNameForSend {
            get {
                return ResourceManager.GetString("ReceiverPartyNameForSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ReuseEnvelope.
        /// </summary>
        public static string ReuseEnvelope {
            get {
                return ResourceManager.GetString("ReuseEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#SenderPartyName.
        /// </summary>
        public static string SenderPartyName {
            get {
                return ResourceManager.GetString("SenderPartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#SenderPartyNameForSend.
        /// </summary>
        public static string SenderPartyNameForSend {
            get {
                return ResourceManager.GetString("SenderPartyNameForSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ST01.
        /// </summary>
        public static string ST01 {
            get {
                return ResourceManager.GetString("ST01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ST03.
        /// </summary>
        public static string ST03 {
            get {
                return ResourceManager.GetString("ST03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#StatusReportContinuationId.
        /// </summary>
        public static string StatusReportContinuationId {
            get {
                return ResourceManager.GetString("StatusReportContinuationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#TA1_TA104.
        /// </summary>
        public static string TA1_TA104 {
            get {
                return ResourceManager.GetString("TA1_TA104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ToBeBatched.
        /// </summary>
        public static string ToBeBatched {
            get {
                return ResourceManager.GetString("ToBeBatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#ToBeRouted.
        /// </summary>
        public static string ToBeRouted {
            get {
                return ResourceManager.GetString("ToBeRouted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#TsSequenceNumberInGroup.
        /// </summary>
        public static string TsSequenceNumberInGroup {
            get {
                return ResourceManager.GetString("TsSequenceNumberInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNA_Segment.
        /// </summary>
        public static string UNA_Segment {
            get {
                return ResourceManager.GetString("UNA_Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB_Segment.
        /// </summary>
        public static string UNB_Segment {
            get {
                return ResourceManager.GetString("UNB_Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB11.
        /// </summary>
        public static string UNB11 {
            get {
                return ResourceManager.GetString("UNB11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB2_1.
        /// </summary>
        public static string UNB2_1 {
            get {
                return ResourceManager.GetString("UNB2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB2_2.
        /// </summary>
        public static string UNB2_2 {
            get {
                return ResourceManager.GetString("UNB2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB2_3.
        /// </summary>
        public static string UNB2_3 {
            get {
                return ResourceManager.GetString("UNB2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB2_4.
        /// </summary>
        public static string UNB2_4 {
            get {
                return ResourceManager.GetString("UNB2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB3_1.
        /// </summary>
        public static string UNB3_1 {
            get {
                return ResourceManager.GetString("UNB3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB3_2.
        /// </summary>
        public static string UNB3_2 {
            get {
                return ResourceManager.GetString("UNB3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB3_3.
        /// </summary>
        public static string UNB3_3 {
            get {
                return ResourceManager.GetString("UNB3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNB3_4.
        /// </summary>
        public static string UNB3_4 {
            get {
                return ResourceManager.GetString("UNB3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNG_Segment.
        /// </summary>
        public static string UNG_Segment {
            get {
                return ResourceManager.GetString("UNG_Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNG1.
        /// </summary>
        public static string UNG1 {
            get {
                return ResourceManager.GetString("UNG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNG2_1.
        /// </summary>
        public static string UNG2_1 {
            get {
                return ResourceManager.GetString("UNG2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNG3_1.
        /// </summary>
        public static string UNG3_1 {
            get {
                return ResourceManager.GetString("UNG3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNH2_1.
        /// </summary>
        public static string UNH2_1 {
            get {
                return ResourceManager.GetString("UNH2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNH2_2.
        /// </summary>
        public static string UNH2_2 {
            get {
                return ResourceManager.GetString("UNH2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema#UNH2_3.
        /// </summary>
        public static string UNH2_3 {
            get {
                return ResourceManager.GetString("UNH2_3", resourceCulture);
            }
        }
    }
}
