//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EDIAS2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EDIAS2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Utils.BizTalkProperties.EDIAS2", typeof(EDIAS2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#AS2From.
        /// </summary>
        public static string AS2From {
            get {
                return ResourceManager.GetString("AS2From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#AS2PayloadContentType.
        /// </summary>
        public static string AS2PayloadContentType {
            get {
                return ResourceManager.GetString("AS2PayloadContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#AS2To.
        /// </summary>
        public static string AS2To {
            get {
                return ResourceManager.GetString("AS2To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#DispositionMode.
        /// </summary>
        public static string DispositionMode {
            get {
                return ResourceManager.GetString("DispositionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#DispositionType.
        /// </summary>
        public static string DispositionType {
            get {
                return ResourceManager.GetString("DispositionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2AsynchronousMdn.
        /// </summary>
        public static string IsAS2AsynchronousMdn {
            get {
                return ResourceManager.GetString("IsAS2AsynchronousMdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2FailedMessage.
        /// </summary>
        public static string IsAS2FailedMessage {
            get {
                return ResourceManager.GetString("IsAS2FailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2Http200OKResponse.
        /// </summary>
        public static string IsAS2Http200OKResponse {
            get {
                return ResourceManager.GetString("IsAS2Http200OKResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2MdnResponseMessage.
        /// </summary>
        public static string IsAS2MdnResponseMessage {
            get {
                return ResourceManager.GetString("IsAS2MdnResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2MessageCompressed.
        /// </summary>
        public static string IsAS2MessageCompressed {
            get {
                return ResourceManager.GetString("IsAS2MessageCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2MessageDuplicate.
        /// </summary>
        public static string IsAS2MessageDuplicate {
            get {
                return ResourceManager.GetString("IsAS2MessageDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2MessageEncrypted.
        /// </summary>
        public static string IsAS2MessageEncrypted {
            get {
                return ResourceManager.GetString("IsAS2MessageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2MessageSigned.
        /// </summary>
        public static string IsAS2MessageSigned {
            get {
                return ResourceManager.GetString("IsAS2MessageSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#IsAS2PayloadMessage.
        /// </summary>
        public static string IsAS2PayloadMessage {
            get {
                return ResourceManager.GetString("IsAS2PayloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#MDNAsyncURI.
        /// </summary>
        public static string MDNAsyncURI {
            get {
                return ResourceManager.GetString("MDNAsyncURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#MessageId.
        /// </summary>
        public static string MessageId {
            get {
                return ResourceManager.GetString("MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#OriginalMessageId.
        /// </summary>
        public static string OriginalMessageId {
            get {
                return ResourceManager.GetString("OriginalMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#PreservedFileName.
        /// </summary>
        public static string PreservedFileName {
            get {
                return ResourceManager.GetString("PreservedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties#SendMDN.
        /// </summary>
        public static string SendMDN {
            get {
                return ResourceManager.GetString("SendMDN", resourceCulture);
            }
        }
    }
}
