//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EDIV2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EDIV2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Utils.BizTalkProperties.EDIV2", typeof(EDIV2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GenerateUNA.
        /// </summary>
        public static string GenerateUNA {
            get {
                return ResourceManager.GetString("GenerateUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GenerateUNG.
        /// </summary>
        public static string GenerateUNG {
            get {
                return ResourceManager.GetString("GenerateUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GS01.
        /// </summary>
        public static string GS01 {
            get {
                return ResourceManager.GetString("GS01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GS02.
        /// </summary>
        public static string GS02 {
            get {
                return ResourceManager.GetString("GS02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GS03.
        /// </summary>
        public static string GS03 {
            get {
                return ResourceManager.GetString("GS03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GS04.
        /// </summary>
        public static string GS04 {
            get {
                return ResourceManager.GetString("GS04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GS05.
        /// </summary>
        public static string GS05 {
            get {
                return ResourceManager.GetString("GS05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GS06.
        /// </summary>
        public static string GS06 {
            get {
                return ResourceManager.GetString("GS06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GS07.
        /// </summary>
        public static string GS07 {
            get {
                return ResourceManager.GetString("GS07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#GS08.
        /// </summary>
        public static string GS08 {
            get {
                return ResourceManager.GetString("GS08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA01.
        /// </summary>
        public static string ISA01 {
            get {
                return ResourceManager.GetString("ISA01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA02.
        /// </summary>
        public static string ISA02 {
            get {
                return ResourceManager.GetString("ISA02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA03.
        /// </summary>
        public static string ISA03 {
            get {
                return ResourceManager.GetString("ISA03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA04.
        /// </summary>
        public static string ISA04 {
            get {
                return ResourceManager.GetString("ISA04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA05.
        /// </summary>
        public static string ISA05 {
            get {
                return ResourceManager.GetString("ISA05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA06.
        /// </summary>
        public static string ISA06 {
            get {
                return ResourceManager.GetString("ISA06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA07.
        /// </summary>
        public static string ISA07 {
            get {
                return ResourceManager.GetString("ISA07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA08.
        /// </summary>
        public static string ISA08 {
            get {
                return ResourceManager.GetString("ISA08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA09.
        /// </summary>
        public static string ISA09 {
            get {
                return ResourceManager.GetString("ISA09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA10.
        /// </summary>
        public static string ISA10 {
            get {
                return ResourceManager.GetString("ISA10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA11.
        /// </summary>
        public static string ISA11 {
            get {
                return ResourceManager.GetString("ISA11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA12.
        /// </summary>
        public static string ISA12 {
            get {
                return ResourceManager.GetString("ISA12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA13.
        /// </summary>
        public static string ISA13 {
            get {
                return ResourceManager.GetString("ISA13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA14.
        /// </summary>
        public static string ISA14 {
            get {
                return ResourceManager.GetString("ISA14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA15.
        /// </summary>
        public static string ISA15 {
            get {
                return ResourceManager.GetString("ISA15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ISA16.
        /// </summary>
        public static string ISA16 {
            get {
                return ResourceManager.GetString("ISA16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#OverrideEDIHeader.
        /// </summary>
        public static string OverrideEDIHeader {
            get {
                return ResourceManager.GetString("OverrideEDIHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#ST02.
        /// </summary>
        public static string ST02 {
            get {
                return ResourceManager.GetString("ST02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNA1.
        /// </summary>
        public static string UNA1 {
            get {
                return ResourceManager.GetString("UNA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNA2.
        /// </summary>
        public static string UNA2 {
            get {
                return ResourceManager.GetString("UNA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNA3.
        /// </summary>
        public static string UNA3 {
            get {
                return ResourceManager.GetString("UNA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNA4.
        /// </summary>
        public static string UNA4 {
            get {
                return ResourceManager.GetString("UNA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNA5.
        /// </summary>
        public static string UNA5 {
            get {
                return ResourceManager.GetString("UNA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNA6.
        /// </summary>
        public static string UNA6 {
            get {
                return ResourceManager.GetString("UNA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNA6Suffix.
        /// </summary>
        public static string UNA6Suffix {
            get {
                return ResourceManager.GetString("UNA6Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB1_1.
        /// </summary>
        public static string UNB1_1 {
            get {
                return ResourceManager.GetString("UNB1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB1_2.
        /// </summary>
        public static string UNB1_2 {
            get {
                return ResourceManager.GetString("UNB1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB1_3.
        /// </summary>
        public static string UNB1_3 {
            get {
                return ResourceManager.GetString("UNB1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB1_4.
        /// </summary>
        public static string UNB1_4 {
            get {
                return ResourceManager.GetString("UNB1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB10.
        /// </summary>
        public static string UNB10 {
            get {
                return ResourceManager.GetString("UNB10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB11.
        /// </summary>
        public static string UNB11 {
            get {
                return ResourceManager.GetString("UNB11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB2_1.
        /// </summary>
        public static string UNB2_1 {
            get {
                return ResourceManager.GetString("UNB2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB2_2.
        /// </summary>
        public static string UNB2_2 {
            get {
                return ResourceManager.GetString("UNB2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB2_3.
        /// </summary>
        public static string UNB2_3 {
            get {
                return ResourceManager.GetString("UNB2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB2_4.
        /// </summary>
        public static string UNB2_4 {
            get {
                return ResourceManager.GetString("UNB2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB3_1.
        /// </summary>
        public static string UNB3_1 {
            get {
                return ResourceManager.GetString("UNB3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB3_2.
        /// </summary>
        public static string UNB3_2 {
            get {
                return ResourceManager.GetString("UNB3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB3_3.
        /// </summary>
        public static string UNB3_3 {
            get {
                return ResourceManager.GetString("UNB3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB3_4.
        /// </summary>
        public static string UNB3_4 {
            get {
                return ResourceManager.GetString("UNB3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB4_1.
        /// </summary>
        public static string UNB4_1 {
            get {
                return ResourceManager.GetString("UNB4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB4_2.
        /// </summary>
        public static string UNB4_2 {
            get {
                return ResourceManager.GetString("UNB4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB5.
        /// </summary>
        public static string UNB5 {
            get {
                return ResourceManager.GetString("UNB5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB6_1.
        /// </summary>
        public static string UNB6_1 {
            get {
                return ResourceManager.GetString("UNB6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB6_2.
        /// </summary>
        public static string UNB6_2 {
            get {
                return ResourceManager.GetString("UNB6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB7.
        /// </summary>
        public static string UNB7 {
            get {
                return ResourceManager.GetString("UNB7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB8.
        /// </summary>
        public static string UNB8 {
            get {
                return ResourceManager.GetString("UNB8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNB9.
        /// </summary>
        public static string UNB9 {
            get {
                return ResourceManager.GetString("UNB9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG1.
        /// </summary>
        public static string UNG1 {
            get {
                return ResourceManager.GetString("UNG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG2_1.
        /// </summary>
        public static string UNG2_1 {
            get {
                return ResourceManager.GetString("UNG2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG2_2.
        /// </summary>
        public static string UNG2_2 {
            get {
                return ResourceManager.GetString("UNG2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG3_1.
        /// </summary>
        public static string UNG3_1 {
            get {
                return ResourceManager.GetString("UNG3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG3_2.
        /// </summary>
        public static string UNG3_2 {
            get {
                return ResourceManager.GetString("UNG3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG4_1.
        /// </summary>
        public static string UNG4_1 {
            get {
                return ResourceManager.GetString("UNG4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG4_2.
        /// </summary>
        public static string UNG4_2 {
            get {
                return ResourceManager.GetString("UNG4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG5.
        /// </summary>
        public static string UNG5 {
            get {
                return ResourceManager.GetString("UNG5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG6.
        /// </summary>
        public static string UNG6 {
            get {
                return ResourceManager.GetString("UNG6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG7_1.
        /// </summary>
        public static string UNG7_1 {
            get {
                return ResourceManager.GetString("UNG7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG7_2.
        /// </summary>
        public static string UNG7_2 {
            get {
                return ResourceManager.GetString("UNG7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG7_3.
        /// </summary>
        public static string UNG7_3 {
            get {
                return ResourceManager.GetString("UNG7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNG8.
        /// </summary>
        public static string UNG8 {
            get {
                return ResourceManager.GetString("UNG8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties#UNH1.
        /// </summary>
        public static string UNH1 {
            get {
                return ResourceManager.GetString("UNH1", resourceCulture);
            }
        }
    }
}
