//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FTP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FTP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Utils.BizTalkProperties.FTP", typeof(FTP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#AfterPut.
        /// </summary>
        public static string AfterPut {
            get {
                return ResourceManager.GetString("AfterPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#AllocateStorage.
        /// </summary>
        public static string AllocateStorage {
            get {
                return ResourceManager.GetString("AllocateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#AppendIfExists.
        /// </summary>
        public static string AppendIfExists {
            get {
                return ResourceManager.GetString("AppendIfExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#BeforePut.
        /// </summary>
        public static string BeforePut {
            get {
                return ResourceManager.GetString("BeforePut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#ClientCertificateHash.
        /// </summary>
        public static string ClientCertificateHash {
            get {
                return ResourceManager.GetString("ClientCertificateHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#CommandLogFileName.
        /// </summary>
        public static string CommandLogFileName {
            get {
                return ResourceManager.GetString("CommandLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#FtpsConnectionMode.
        /// </summary>
        public static string FtpsConnectionMode {
            get {
                return ResourceManager.GetString("FtpsConnectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#FtpServerType.
        /// </summary>
        public static string FtpServerType {
            get {
                return ResourceManager.GetString("FtpServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#MaxConnections.
        /// </summary>
        public static string MaxConnections {
            get {
                return ResourceManager.GetString("MaxConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#PassiveMode.
        /// </summary>
        public static string PassiveMode {
            get {
                return ResourceManager.GetString("PassiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#ReceivedFileName.
        /// </summary>
        public static string ReceivedFileName {
            get {
                return ResourceManager.GetString("ReceivedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#RepresentationType.
        /// </summary>
        public static string RepresentationType {
            get {
                return ResourceManager.GetString("RepresentationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#SpoolingFolder.
        /// </summary>
        public static string SpoolingFolder {
            get {
                return ResourceManager.GetString("SpoolingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#SSOAffiliateApplication.
        /// </summary>
        public static string SSOAffiliateApplication {
            get {
                return ResourceManager.GetString("SSOAffiliateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#UseDataProtection.
        /// </summary>
        public static string UseDataProtection {
            get {
                return ResourceManager.GetString("UseDataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties#UseSsl.
        /// </summary>
        public static string UseSsl {
            get {
                return ResourceManager.GetString("UseSsl", resourceCulture);
            }
        }
    }
}
