//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MIME {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MIME() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.MIME", typeof(MIME).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#ContentDescription.
        /// </summary>
        public static string ContentDescription {
            get {
                return ResourceManager.GetString("ContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#ContentID.
        /// </summary>
        public static string ContentID {
            get {
                return ResourceManager.GetString("ContentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#ContentLocation.
        /// </summary>
        public static string ContentLocation {
            get {
                return ResourceManager.GetString("ContentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#ContentTransferEncoding.
        /// </summary>
        public static string ContentTransferEncoding {
            get {
                return ResourceManager.GetString("ContentTransferEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#ContentTypeSecondaryHeader.
        /// </summary>
        public static string ContentTypeSecondaryHeader {
            get {
                return ResourceManager.GetString("ContentTypeSecondaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#ContentTypeSecondaryHeaderValue.
        /// </summary>
        public static string ContentTypeSecondaryHeaderValue {
            get {
                return ResourceManager.GetString("ContentTypeSecondaryHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#FileName.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#IsMIMEEncoded.
        /// </summary>
        public static string IsMIMEEncoded {
            get {
                return ResourceManager.GetString("IsMIMEEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#IsMultipartRelated.
        /// </summary>
        public static string IsMultipartRelated {
            get {
                return ResourceManager.GetString("IsMultipartRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#PartContentTypeSecondaryHeader.
        /// </summary>
        public static string PartContentTypeSecondaryHeader {
            get {
                return ResourceManager.GetString("PartContentTypeSecondaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#PartContentTypeSecondaryHeaderValue.
        /// </summary>
        public static string PartContentTypeSecondaryHeaderValue {
            get {
                return ResourceManager.GetString("PartContentTypeSecondaryHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties#PassThroughBTF.
        /// </summary>
        public static string PassThroughBTF {
            get {
                return ResourceManager.GetString("PassThroughBTF", resourceCulture);
            }
        }
    }
}
