//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MQSeries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MQSeries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.MQSeries", typeof(MQSeries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#BizTalk_CorrelationID.
        /// </summary>
        public static string BizTalk_CorrelationID {
            get {
                return ResourceManager.GetString("BizTalk_CorrelationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#CompleteMessage.
        /// </summary>
        public static string CompleteMessage {
            get {
                return ResourceManager.GetString("CompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#DataConversion.
        /// </summary>
        public static string DataConversion {
            get {
                return ResourceManager.GetString("DataConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#DynamicReceive.
        /// </summary>
        public static string DynamicReceive {
            get {
                return ResourceManager.GetString("DynamicReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_AbendCode.
        /// </summary>
        public static string MQCIH_AbendCode {
            get {
                return ResourceManager.GetString("MQCIH_AbendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_ADSDescriptor.
        /// </summary>
        public static string MQCIH_ADSDescriptor {
            get {
                return ResourceManager.GetString("MQCIH_ADSDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_AttentionId.
        /// </summary>
        public static string MQCIH_AttentionId {
            get {
                return ResourceManager.GetString("MQCIH_AttentionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_Authenticator.
        /// </summary>
        public static string MQCIH_Authenticator {
            get {
                return ResourceManager.GetString("MQCIH_Authenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_CancelCode.
        /// </summary>
        public static string MQCIH_CancelCode {
            get {
                return ResourceManager.GetString("MQCIH_CancelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_CompCode.
        /// </summary>
        public static string MQCIH_CompCode {
            get {
                return ResourceManager.GetString("MQCIH_CompCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_ConversationalTask.
        /// </summary>
        public static string MQCIH_ConversationalTask {
            get {
                return ResourceManager.GetString("MQCIH_ConversationalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_CursorPosition.
        /// </summary>
        public static string MQCIH_CursorPosition {
            get {
                return ResourceManager.GetString("MQCIH_CursorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_ErrorOffset.
        /// </summary>
        public static string MQCIH_ErrorOffset {
            get {
                return ResourceManager.GetString("MQCIH_ErrorOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_Facility.
        /// </summary>
        public static string MQCIH_Facility {
            get {
                return ResourceManager.GetString("MQCIH_Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_FacilityKeepTime.
        /// </summary>
        public static string MQCIH_FacilityKeepTime {
            get {
                return ResourceManager.GetString("MQCIH_FacilityKeepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_FacilityLike.
        /// </summary>
        public static string MQCIH_FacilityLike {
            get {
                return ResourceManager.GetString("MQCIH_FacilityLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_Flags.
        /// </summary>
        public static string MQCIH_Flags {
            get {
                return ResourceManager.GetString("MQCIH_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_Format.
        /// </summary>
        public static string MQCIH_Format {
            get {
                return ResourceManager.GetString("MQCIH_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_Function.
        /// </summary>
        public static string MQCIH_Function {
            get {
                return ResourceManager.GetString("MQCIH_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_GetWaitInterval.
        /// </summary>
        public static string MQCIH_GetWaitInterval {
            get {
                return ResourceManager.GetString("MQCIH_GetWaitInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_LinkType.
        /// </summary>
        public static string MQCIH_LinkType {
            get {
                return ResourceManager.GetString("MQCIH_LinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_NextTransactionId.
        /// </summary>
        public static string MQCIH_NextTransactionId {
            get {
                return ResourceManager.GetString("MQCIH_NextTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_OutputDataLength.
        /// </summary>
        public static string MQCIH_OutputDataLength {
            get {
                return ResourceManager.GetString("MQCIH_OutputDataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_Reason.
        /// </summary>
        public static string MQCIH_Reason {
            get {
                return ResourceManager.GetString("MQCIH_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_ReplyToFormat.
        /// </summary>
        public static string MQCIH_ReplyToFormat {
            get {
                return ResourceManager.GetString("MQCIH_ReplyToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_ReturnCode.
        /// </summary>
        public static string MQCIH_ReturnCode {
            get {
                return ResourceManager.GetString("MQCIH_ReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_StartCode.
        /// </summary>
        public static string MQCIH_StartCode {
            get {
                return ResourceManager.GetString("MQCIH_StartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_TaskEndStatus.
        /// </summary>
        public static string MQCIH_TaskEndStatus {
            get {
                return ResourceManager.GetString("MQCIH_TaskEndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_TransactionId.
        /// </summary>
        public static string MQCIH_TransactionId {
            get {
                return ResourceManager.GetString("MQCIH_TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQCIH_UOWControl.
        /// </summary>
        public static string MQCIH_UOWControl {
            get {
                return ResourceManager.GetString("MQCIH_UOWControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_Authenticator.
        /// </summary>
        public static string MQIIH_Authenticator {
            get {
                return ResourceManager.GetString("MQIIH_Authenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_CommitMode.
        /// </summary>
        public static string MQIIH_CommitMode {
            get {
                return ResourceManager.GetString("MQIIH_CommitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_Flags.
        /// </summary>
        public static string MQIIH_Flags {
            get {
                return ResourceManager.GetString("MQIIH_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_Format.
        /// </summary>
        public static string MQIIH_Format {
            get {
                return ResourceManager.GetString("MQIIH_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_LTermOverride.
        /// </summary>
        public static string MQIIH_LTermOverride {
            get {
                return ResourceManager.GetString("MQIIH_LTermOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_MFSMapName.
        /// </summary>
        public static string MQIIH_MFSMapName {
            get {
                return ResourceManager.GetString("MQIIH_MFSMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_ReplyToFormat.
        /// </summary>
        public static string MQIIH_ReplyToFormat {
            get {
                return ResourceManager.GetString("MQIIH_ReplyToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_SecurityScope.
        /// </summary>
        public static string MQIIH_SecurityScope {
            get {
                return ResourceManager.GetString("MQIIH_SecurityScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_TranInstanceId.
        /// </summary>
        public static string MQIIH_TranInstanceId {
            get {
                return ResourceManager.GetString("MQIIH_TranInstanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQIIH_TranState.
        /// </summary>
        public static string MQIIH_TranState {
            get {
                return ResourceManager.GetString("MQIIH_TranState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_AccountingToken.
        /// </summary>
        public static string MQMD_AccountingToken {
            get {
                return ResourceManager.GetString("MQMD_AccountingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_ApplIdentityData.
        /// </summary>
        public static string MQMD_ApplIdentityData {
            get {
                return ResourceManager.GetString("MQMD_ApplIdentityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_ApplOriginData.
        /// </summary>
        public static string MQMD_ApplOriginData {
            get {
                return ResourceManager.GetString("MQMD_ApplOriginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_BackoutCount.
        /// </summary>
        public static string MQMD_BackoutCount {
            get {
                return ResourceManager.GetString("MQMD_BackoutCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_CodedCharSetId.
        /// </summary>
        public static string MQMD_CodedCharSetId {
            get {
                return ResourceManager.GetString("MQMD_CodedCharSetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_CorrelId.
        /// </summary>
        public static string MQMD_CorrelId {
            get {
                return ResourceManager.GetString("MQMD_CorrelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_Encoding.
        /// </summary>
        public static string MQMD_Encoding {
            get {
                return ResourceManager.GetString("MQMD_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_Expiry.
        /// </summary>
        public static string MQMD_Expiry {
            get {
                return ResourceManager.GetString("MQMD_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_Feedback.
        /// </summary>
        public static string MQMD_Feedback {
            get {
                return ResourceManager.GetString("MQMD_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_Format.
        /// </summary>
        public static string MQMD_Format {
            get {
                return ResourceManager.GetString("MQMD_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_GroupId.
        /// </summary>
        public static string MQMD_GroupId {
            get {
                return ResourceManager.GetString("MQMD_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_MsgFlags.
        /// </summary>
        public static string MQMD_MsgFlags {
            get {
                return ResourceManager.GetString("MQMD_MsgFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_MsgId.
        /// </summary>
        public static string MQMD_MsgId {
            get {
                return ResourceManager.GetString("MQMD_MsgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_MsgSeqNumber.
        /// </summary>
        public static string MQMD_MsgSeqNumber {
            get {
                return ResourceManager.GetString("MQMD_MsgSeqNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_MsgType.
        /// </summary>
        public static string MQMD_MsgType {
            get {
                return ResourceManager.GetString("MQMD_MsgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_Offset.
        /// </summary>
        public static string MQMD_Offset {
            get {
                return ResourceManager.GetString("MQMD_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_OriginalLength.
        /// </summary>
        public static string MQMD_OriginalLength {
            get {
                return ResourceManager.GetString("MQMD_OriginalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_Persistence.
        /// </summary>
        public static string MQMD_Persistence {
            get {
                return ResourceManager.GetString("MQMD_Persistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_Priority.
        /// </summary>
        public static string MQMD_Priority {
            get {
                return ResourceManager.GetString("MQMD_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_PutApplName.
        /// </summary>
        public static string MQMD_PutApplName {
            get {
                return ResourceManager.GetString("MQMD_PutApplName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_PutApplType.
        /// </summary>
        public static string MQMD_PutApplType {
            get {
                return ResourceManager.GetString("MQMD_PutApplType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_PutDate.
        /// </summary>
        public static string MQMD_PutDate {
            get {
                return ResourceManager.GetString("MQMD_PutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_PutTime.
        /// </summary>
        public static string MQMD_PutTime {
            get {
                return ResourceManager.GetString("MQMD_PutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_ReplyToQ.
        /// </summary>
        public static string MQMD_ReplyToQ {
            get {
                return ResourceManager.GetString("MQMD_ReplyToQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_ReplyToQMgr.
        /// </summary>
        public static string MQMD_ReplyToQMgr {
            get {
                return ResourceManager.GetString("MQMD_ReplyToQMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_Report.
        /// </summary>
        public static string MQMD_Report {
            get {
                return ResourceManager.GetString("MQMD_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQMD_UserIdentifier.
        /// </summary>
        public static string MQMD_UserIdentifier {
            get {
                return ResourceManager.GetString("MQMD_UserIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_AccountingToken.
        /// </summary>
        public static string MQXQH_MsgDesc_AccountingToken {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_AccountingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_ApplIdentityData.
        /// </summary>
        public static string MQXQH_MsgDesc_ApplIdentityData {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_ApplIdentityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_ApplOriginData.
        /// </summary>
        public static string MQXQH_MsgDesc_ApplOriginData {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_ApplOriginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_BackoutCount.
        /// </summary>
        public static string MQXQH_MsgDesc_BackoutCount {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_BackoutCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_CodedCharSetId.
        /// </summary>
        public static string MQXQH_MsgDesc_CodedCharSetId {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_CodedCharSetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_CorrelId.
        /// </summary>
        public static string MQXQH_MsgDesc_CorrelId {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_CorrelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_Encoding.
        /// </summary>
        public static string MQXQH_MsgDesc_Encoding {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_Expiry.
        /// </summary>
        public static string MQXQH_MsgDesc_Expiry {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_Feedback.
        /// </summary>
        public static string MQXQH_MsgDesc_Feedback {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_Format.
        /// </summary>
        public static string MQXQH_MsgDesc_Format {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_MsgId.
        /// </summary>
        public static string MQXQH_MsgDesc_MsgId {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_MsgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_MsgType.
        /// </summary>
        public static string MQXQH_MsgDesc_MsgType {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_MsgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_Persistence.
        /// </summary>
        public static string MQXQH_MsgDesc_Persistence {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_Persistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_Priority.
        /// </summary>
        public static string MQXQH_MsgDesc_Priority {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_PutApplName.
        /// </summary>
        public static string MQXQH_MsgDesc_PutApplName {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_PutApplName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_PutApplType.
        /// </summary>
        public static string MQXQH_MsgDesc_PutApplType {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_PutApplType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_PutDate.
        /// </summary>
        public static string MQXQH_MsgDesc_PutDate {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_PutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_PutTime.
        /// </summary>
        public static string MQXQH_MsgDesc_PutTime {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_PutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_ReplyToQ.
        /// </summary>
        public static string MQXQH_MsgDesc_ReplyToQ {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_ReplyToQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_ReplyToQMgr.
        /// </summary>
        public static string MQXQH_MsgDesc_ReplyToQMgr {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_ReplyToQMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_Report.
        /// </summary>
        public static string MQXQH_MsgDesc_Report {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_MsgDesc_UserIdentifier.
        /// </summary>
        public static string MQXQH_MsgDesc_UserIdentifier {
            get {
                return ResourceManager.GetString("MQXQH_MsgDesc_UserIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_RemoteQMgrName.
        /// </summary>
        public static string MQXQH_RemoteQMgrName {
            get {
                return ResourceManager.GetString("MQXQH_RemoteQMgrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#MQXQH_RemoteQName.
        /// </summary>
        public static string MQXQH_RemoteQName {
            get {
                return ResourceManager.GetString("MQXQH_RemoteQName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#Ordered.
        /// </summary>
        public static string Ordered {
            get {
                return ResourceManager.GetString("Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#SegmentationAllowed.
        /// </summary>
        public static string SegmentationAllowed {
            get {
                return ResourceManager.GetString("SegmentationAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#SSOAffiliateApplication.
        /// </summary>
        public static string SSOAffiliateApplication {
            get {
                return ResourceManager.GetString("SSOAffiliateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#TransactionSupported.
        /// </summary>
        public static string TransactionSupported {
            get {
                return ResourceManager.GetString("TransactionSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties#WaitInterval.
        /// </summary>
        public static string WaitInterval {
            get {
                return ResourceManager.GetString("WaitInterval", resourceCulture);
            }
        }
    }
}
