//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MSMQT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSMQT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.MSMQT", typeof(MSMQT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Acknowledge.
        /// </summary>
        public static string Acknowledge {
            get {
                return ResourceManager.GetString("Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#AdminQueue.
        /// </summary>
        public static string AdminQueue {
            get {
                return ResourceManager.GetString("AdminQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#AppSpecific.
        /// </summary>
        public static string AppSpecific {
            get {
                return ResourceManager.GetString("AppSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#ArrivedTime.
        /// </summary>
        public static string ArrivedTime {
            get {
                return ResourceManager.GetString("ArrivedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Audit.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Authenticated.
        /// </summary>
        public static string Authenticated {
            get {
                return ResourceManager.GetString("Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#AuthLevel.
        /// </summary>
        public static string AuthLevel {
            get {
                return ResourceManager.GetString("AuthLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#CorrelationId.
        /// </summary>
        public static string CorrelationId {
            get {
                return ResourceManager.GetString("CorrelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#DestinationQueue.
        /// </summary>
        public static string DestinationQueue {
            get {
                return ResourceManager.GetString("DestinationQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#EncryptionAlgorithm.
        /// </summary>
        public static string EncryptionAlgorithm {
            get {
                return ResourceManager.GetString("EncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#FragmentN.
        /// </summary>
        public static string FragmentN {
            get {
                return ResourceManager.GetString("FragmentN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#HashAlg.
        /// </summary>
        public static string HashAlg {
            get {
                return ResourceManager.GetString("HashAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#InboundCorrelationId.
        /// </summary>
        public static string InboundCorrelationId {
            get {
                return ResourceManager.GetString("InboundCorrelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#InboundResponseQueue.
        /// </summary>
        public static string InboundResponseQueue {
            get {
                return ResourceManager.GetString("InboundResponseQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#IsAuthenticated.
        /// </summary>
        public static string IsAuthenticated {
            get {
                return ResourceManager.GetString("IsAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#IsFirstInTransaction.
        /// </summary>
        public static string IsFirstInTransaction {
            get {
                return ResourceManager.GetString("IsFirstInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#IsLastInTransaction.
        /// </summary>
        public static string IsLastInTransaction {
            get {
                return ResourceManager.GetString("IsLastInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#IsSecurityIncluded.
        /// </summary>
        public static string IsSecurityIncluded {
            get {
                return ResourceManager.GetString("IsSecurityIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#IsXactMsg.
        /// </summary>
        public static string IsXactMsg {
            get {
                return ResourceManager.GetString("IsXactMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#LastFragment.
        /// </summary>
        public static string LastFragment {
            get {
                return ResourceManager.GetString("LastFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#MessageType.
        /// </summary>
        public static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#MsgID.
        /// </summary>
        public static string MsgID {
            get {
                return ResourceManager.GetString("MsgID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#NonTransactionalQueue.
        /// </summary>
        public static string NonTransactionalQueue {
            get {
                return ResourceManager.GetString("NonTransactionalQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#OrderQueue.
        /// </summary>
        public static string OrderQueue {
            get {
                return ResourceManager.GetString("OrderQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#OutboundTransportLocation.
        /// </summary>
        public static string OutboundTransportLocation {
            get {
                return ResourceManager.GetString("OutboundTransportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#PrevN.
        /// </summary>
        public static string PrevN {
            get {
                return ResourceManager.GetString("PrevN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#PrivLevel.
        /// </summary>
        public static string PrivLevel {
            get {
                return ResourceManager.GetString("PrivLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#ResponseQueue.
        /// </summary>
        public static string ResponseQueue {
            get {
                return ResourceManager.GetString("ResponseQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#RouterName.
        /// </summary>
        public static string RouterName {
            get {
                return ResourceManager.GetString("RouterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#SenderID.
        /// </summary>
        public static string SenderID {
            get {
                return ResourceManager.GetString("SenderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#SenderIDLength.
        /// </summary>
        public static string SenderIDLength {
            get {
                return ResourceManager.GetString("SenderIDLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#SenderIDType.
        /// </summary>
        public static string SenderIDType {
            get {
                return ResourceManager.GetString("SenderIDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#SentTime.
        /// </summary>
        public static string SentTime {
            get {
                return ResourceManager.GetString("SentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#SeqID.
        /// </summary>
        public static string SeqID {
            get {
                return ResourceManager.GetString("SeqID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#SeqN.
        /// </summary>
        public static string SeqN {
            get {
                return ResourceManager.GetString("SeqN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#SignatureSize.
        /// </summary>
        public static string SignatureSize {
            get {
                return ResourceManager.GetString("SignatureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#SourceMachineGuid.
        /// </summary>
        public static string SourceMachineGuid {
            get {
                return ResourceManager.GetString("SourceMachineGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#TimerChain.
        /// </summary>
        public static string TimerChain {
            get {
                return ResourceManager.GetString("TimerChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#TimeToReachQueue.
        /// </summary>
        public static string TimeToReachQueue {
            get {
                return ResourceManager.GetString("TimeToReachQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Trace.
        /// </summary>
        public static string Trace {
            get {
                return ResourceManager.GetString("Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#TransactionId.
        /// </summary>
        public static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties#WakeupTime.
        /// </summary>
        public static string WakeupTime {
            get {
                return ResourceManager.GetString("WakeupTime", resourceCulture);
            }
        }
    }
}
