//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MSMQ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSMQ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.MSMQ", typeof(MSMQ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#Acknowledgement.
        /// </summary>
        public static string Acknowledgement {
            get {
                return ResourceManager.GetString("Acknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#AcknowledgeType.
        /// </summary>
        public static string AcknowledgeType {
            get {
                return ResourceManager.GetString("AcknowledgeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#AdministrationQueue.
        /// </summary>
        public static string AdministrationQueue {
            get {
                return ResourceManager.GetString("AdministrationQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#AppSpecific.
        /// </summary>
        public static string AppSpecific {
            get {
                return ResourceManager.GetString("AppSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#ArrivedTime.
        /// </summary>
        public static string ArrivedTime {
            get {
                return ResourceManager.GetString("ArrivedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#Authenticated.
        /// </summary>
        public static string Authenticated {
            get {
                return ResourceManager.GetString("Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#BodyType.
        /// </summary>
        public static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#CertificateThumbPrint.
        /// </summary>
        public static string CertificateThumbPrint {
            get {
                return ResourceManager.GetString("CertificateThumbPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#CorrelationId.
        /// </summary>
        public static string CorrelationId {
            get {
                return ResourceManager.GetString("CorrelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#EncryptionAlgorithm.
        /// </summary>
        public static string EncryptionAlgorithm {
            get {
                return ResourceManager.GetString("EncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#MaximumMessageSize.
        /// </summary>
        public static string MaximumMessageSize {
            get {
                return ResourceManager.GetString("MaximumMessageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#MessageType.
        /// </summary>
        public static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#Recoverable.
        /// </summary>
        public static string Recoverable {
            get {
                return ResourceManager.GetString("Recoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#ResponseQueue.
        /// </summary>
        public static string ResponseQueue {
            get {
                return ResourceManager.GetString("ResponseQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#SegmentationSupport.
        /// </summary>
        public static string SegmentationSupport {
            get {
                return ResourceManager.GetString("SegmentationSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#SentTime.
        /// </summary>
        public static string SentTime {
            get {
                return ResourceManager.GetString("SentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#SourceMachine.
        /// </summary>
        public static string SourceMachine {
            get {
                return ResourceManager.GetString("SourceMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#TimeOut.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#TimeOutUnits.
        /// </summary>
        public static string TimeOutUnits {
            get {
                return ResourceManager.GetString("TimeOutUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#Transactional.
        /// </summary>
        public static string Transactional {
            get {
                return ResourceManager.GetString("Transactional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#UseAuthentication.
        /// </summary>
        public static string UseAuthentication {
            get {
                return ResourceManager.GetString("UseAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#UseDeadLetterQueue.
        /// </summary>
        public static string UseDeadLetterQueue {
            get {
                return ResourceManager.GetString("UseDeadLetterQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties#UseJournalQueue.
        /// </summary>
        public static string UseJournalQueue {
            get {
                return ResourceManager.GetString("UseJournalQueue", resourceCulture);
            }
        }
    }
}
