//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Namespaces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Namespaces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.Namespaces", typeof(Namespaces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties/appstream.
        /// </summary>
        public static string AppStream {
            get {
                return ResourceManager.GetString("AppStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties.
        /// </summary>
        public static string BTS {
            get {
                return ResourceManager.GetString("BTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/Edi/PropertySchema.
        /// </summary>
        public static string EDI {
            get {
                return ResourceManager.GetString("EDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/as2-properties.
        /// </summary>
        public static string EDIAS2 {
            get {
                return ResourceManager.GetString("EDIAS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/edi-properties.
        /// </summary>
        public static string EDIV2 {
            get {
                return ResourceManager.GetString("EDIV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/file-properties.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/ftp-properties.
        /// </summary>
        public static string FTP {
            get {
                return ResourceManager.GetString("FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/http-properties.
        /// </summary>
        public static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mime-properties.
        /// </summary>
        public static string MIME {
            get {
                return ResourceManager.GetString("MIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/mqs-properties.
        /// </summary>
        public static string MQSeries {
            get {
                return ResourceManager.GetString("MQSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmq-properties.
        /// </summary>
        public static string MSMQ {
            get {
                return ResourceManager.GetString("MSMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/msmqt-properties.
        /// </summary>
        public static string MSMQT {
            get {
                return ResourceManager.GetString("MSMQT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/pop3-properties.
        /// </summary>
        public static string POP3 {
            get {
                return ResourceManager.GetString("POP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties.
        /// </summary>
        public static string ServiceBus {
            get {
                return ResourceManager.GetString("ServiceBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/sftp-properties.
        /// </summary>
        public static string SFTP {
            get {
                return ResourceManager.GetString("SFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/smtp-properties.
        /// </summary>
        public static string SMTP {
            get {
                return ResourceManager.GetString("SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties.
        /// </summary>
        public static string SOAP {
            get {
                return ResourceManager.GetString("SOAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/sql-properties.
        /// </summary>
        public static string SQL {
            get {
                return ResourceManager.GetString("SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties.
        /// </summary>
        public static string WCF {
            get {
                return ResourceManager.GetString("WCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties.
        /// </summary>
        public static string WSS {
            get {
                return ResourceManager.GetString("WSS", resourceCulture);
            }
        }
    }
}
