//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceBus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceBus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.ServiceBus", typeof(ServiceBus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#ContentType.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#CorrelationId.
        /// </summary>
        public static string CorrelationId {
            get {
                return ResourceManager.GetString("CorrelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#CustomBrokeredMessagePropertyNamespace.
        /// </summary>
        public static string CustomBrokeredMessagePropertyNamespace {
            get {
                return ResourceManager.GetString("CustomBrokeredMessagePropertyNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#DeliveryCount.
        /// </summary>
        public static string DeliveryCount {
            get {
                return ResourceManager.GetString("DeliveryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#EnqueuedTimeUtc.
        /// </summary>
        public static string EnqueuedTimeUtc {
            get {
                return ResourceManager.GetString("EnqueuedTimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#ExpiresAtUtc.
        /// </summary>
        public static string ExpiresAtUtc {
            get {
                return ResourceManager.GetString("ExpiresAtUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#LockedUntilUtc.
        /// </summary>
        public static string LockedUntilUtc {
            get {
                return ResourceManager.GetString("LockedUntilUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#LockToken.
        /// </summary>
        public static string LockToken {
            get {
                return ResourceManager.GetString("LockToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#MessageId.
        /// </summary>
        public static string MessageId {
            get {
                return ResourceManager.GetString("MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#ReplyTo.
        /// </summary>
        public static string ReplyTo {
            get {
                return ResourceManager.GetString("ReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#ReplyToSessionId.
        /// </summary>
        public static string ReplyToSessionId {
            get {
                return ResourceManager.GetString("ReplyToSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#ScheduledEnqueueTimeUtc.
        /// </summary>
        public static string ScheduledEnqueueTimeUtc {
            get {
                return ResourceManager.GetString("ScheduledEnqueueTimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#SequenceNumber.
        /// </summary>
        public static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#SessionId.
        /// </summary>
        public static string SessionId {
            get {
                return ResourceManager.GetString("SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#TimeToLive.
        /// </summary>
        public static string TimeToLive {
            get {
                return ResourceManager.GetString("TimeToLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2012/Adapter/BrokeredMessage-properties#To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
