//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SOAP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SOAP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Utils.BizTalkProperties.SOAP", typeof(SOAP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#AffiliateApplicationName.
        /// </summary>
        public static string AffiliateApplicationName {
            get {
                return ResourceManager.GetString("AffiliateApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#AssemblyName.
        /// </summary>
        public static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#AuthenticationScheme.
        /// </summary>
        public static string AuthenticationScheme {
            get {
                return ResourceManager.GetString("AuthenticationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#ClientCertificate.
        /// </summary>
        public static string ClientCertificate {
            get {
                return ResourceManager.GetString("ClientCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#ClientConnectionTimeout.
        /// </summary>
        public static string ClientConnectionTimeout {
            get {
                return ResourceManager.GetString("ClientConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#MethodName.
        /// </summary>
        public static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#ProxyAddress.
        /// </summary>
        public static string ProxyAddress {
            get {
                return ResourceManager.GetString("ProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#ProxyPassword.
        /// </summary>
        public static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#ProxyPort.
        /// </summary>
        public static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#ProxyUsername.
        /// </summary>
        public static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#TypeName.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#UnknownHeaders.
        /// </summary>
        public static string UnknownHeaders {
            get {
                return ResourceManager.GetString("UnknownHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#UseHandlerSetting.
        /// </summary>
        public static string UseHandlerSetting {
            get {
                return ResourceManager.GetString("UseHandlerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#UseProxy.
        /// </summary>
        public static string UseProxy {
            get {
                return ResourceManager.GetString("UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#UserDefined.
        /// </summary>
        public static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#UseSoap12.
        /// </summary>
        public static string UseSoap12 {
            get {
                return ResourceManager.GetString("UseSoap12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/soap-properties#UseSSO.
        /// </summary>
        public static string UseSSO {
            get {
                return ResourceManager.GetString("UseSSO", resourceCulture);
            }
        }
    }
}
