//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WCF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WCF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.WCF", typeof(WCF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#AffiliateApplicationName.
        /// </summary>
        public static string AffiliateApplicationName {
            get {
                return ResourceManager.GetString("AffiliateApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#AlgorithmSuite.
        /// </summary>
        public static string AlgorithmSuite {
            get {
                return ResourceManager.GetString("AlgorithmSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#BindingConfiguration.
        /// </summary>
        public static string BindingConfiguration {
            get {
                return ResourceManager.GetString("BindingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#BindingType.
        /// </summary>
        public static string BindingType {
            get {
                return ResourceManager.GetString("BindingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ClientCertificate.
        /// </summary>
        public static string ClientCertificate {
            get {
                return ResourceManager.GetString("ClientCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#CloseTimeout.
        /// </summary>
        public static string CloseTimeout {
            get {
                return ResourceManager.GetString("CloseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#CustomDeadLetterQueue.
        /// </summary>
        public static string CustomDeadLetterQueue {
            get {
                return ResourceManager.GetString("CustomDeadLetterQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#DeadLetterQueue.
        /// </summary>
        public static string DeadLetterQueue {
            get {
                return ResourceManager.GetString("DeadLetterQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#DisableLocationOnFailure.
        /// </summary>
        public static string DisableLocationOnFailure {
            get {
                return ResourceManager.GetString("DisableLocationOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#EnableTransaction.
        /// </summary>
        public static string EnableTransaction {
            get {
                return ResourceManager.GetString("EnableTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#EndpointBehaviorConfiguration.
        /// </summary>
        public static string EndpointBehaviorConfiguration {
            get {
                return ResourceManager.GetString("EndpointBehaviorConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#EstablishSecurityContext.
        /// </summary>
        public static string EstablishSecurityContext {
            get {
                return ResourceManager.GetString("EstablishSecurityContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#FromAddress.
        /// </summary>
        public static string FromAddress {
            get {
                return ResourceManager.GetString("FromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#Headers.
        /// </summary>
        public static string Headers {
            get {
                return ResourceManager.GetString("Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#HttpHeaders.
        /// </summary>
        public static string HttpHeaders {
            get {
                return ResourceManager.GetString("HttpHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#HttpMethodAndUrl.
        /// </summary>
        public static string HttpMethodAndUrl {
            get {
                return ResourceManager.GetString("HttpMethodAndUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#Identity.
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#InboundBodyLocation.
        /// </summary>
        public static string InboundBodyLocation {
            get {
                return ResourceManager.GetString("InboundBodyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#InboundBodyPathExpression.
        /// </summary>
        public static string InboundBodyPathExpression {
            get {
                return ResourceManager.GetString("InboundBodyPathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#InboundHeaders.
        /// </summary>
        public static string InboundHeaders {
            get {
                return ResourceManager.GetString("InboundHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#InboundHttpHeaders.
        /// </summary>
        public static string InboundHttpHeaders {
            get {
                return ResourceManager.GetString("InboundHttpHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#InboundHttpMethod.
        /// </summary>
        public static string InboundHttpMethod {
            get {
                return ResourceManager.GetString("InboundHttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#InboundHttpStatusCode.
        /// </summary>
        public static string InboundHttpStatusCode {
            get {
                return ResourceManager.GetString("InboundHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#InboundHttpStatusDescription.
        /// </summary>
        public static string InboundHttpStatusDescription {
            get {
                return ResourceManager.GetString("InboundHttpStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#InboundNodeEncoding.
        /// </summary>
        public static string InboundNodeEncoding {
            get {
                return ResourceManager.GetString("InboundNodeEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#IsFault.
        /// </summary>
        public static string IsFault {
            get {
                return ResourceManager.GetString("IsFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#IsolationLevel.
        /// </summary>
        public static string IsolationLevel {
            get {
                return ResourceManager.GetString("IsolationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#IssuerName.
        /// </summary>
        public static string IssuerName {
            get {
                return ResourceManager.GetString("IssuerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#IssuerSecret.
        /// </summary>
        public static string IssuerSecret {
            get {
                return ResourceManager.GetString("IssuerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#LeaseTimeout.
        /// </summary>
        public static string LeaseTimeout {
            get {
                return ResourceManager.GetString("LeaseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MaxConcurrentCalls.
        /// </summary>
        public static string MaxConcurrentCalls {
            get {
                return ResourceManager.GetString("MaxConcurrentCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MaxConnections.
        /// </summary>
        public static string MaxConnections {
            get {
                return ResourceManager.GetString("MaxConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MaxReceivedMessageSize.
        /// </summary>
        public static string MaxReceivedMessageSize {
            get {
                return ResourceManager.GetString("MaxReceivedMessageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MessageClientCredentialType.
        /// </summary>
        public static string MessageClientCredentialType {
            get {
                return ResourceManager.GetString("MessageClientCredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MessageEncoding.
        /// </summary>
        public static string MessageEncoding {
            get {
                return ResourceManager.GetString("MessageEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MsmqAuthenticationMode.
        /// </summary>
        public static string MsmqAuthenticationMode {
            get {
                return ResourceManager.GetString("MsmqAuthenticationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MsmqEncryptionAlgorithm.
        /// </summary>
        public static string MsmqEncryptionAlgorithm {
            get {
                return ResourceManager.GetString("MsmqEncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MsmqProtectionLevel.
        /// </summary>
        public static string MsmqProtectionLevel {
            get {
                return ResourceManager.GetString("MsmqProtectionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#MsmqSecureHashAlgorithm.
        /// </summary>
        public static string MsmqSecureHashAlgorithm {
            get {
                return ResourceManager.GetString("MsmqSecureHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#NegotiateServiceCredential.
        /// </summary>
        public static string NegotiateServiceCredential {
            get {
                return ResourceManager.GetString("NegotiateServiceCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#OpenTimeout.
        /// </summary>
        public static string OpenTimeout {
            get {
                return ResourceManager.GetString("OpenTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#OrderedProcessing.
        /// </summary>
        public static string OrderedProcessing {
            get {
                return ResourceManager.GetString("OrderedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#OutboundBodyLocation.
        /// </summary>
        public static string OutboundBodyLocation {
            get {
                return ResourceManager.GetString("OutboundBodyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#OutboundCustomHeaders.
        /// </summary>
        public static string OutboundCustomHeaders {
            get {
                return ResourceManager.GetString("OutboundCustomHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#OutboundHttpStatusCode.
        /// </summary>
        public static string OutboundHttpStatusCode {
            get {
                return ResourceManager.GetString("OutboundHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#OutboundHttpStatusDescription.
        /// </summary>
        public static string OutboundHttpStatusDescription {
            get {
                return ResourceManager.GetString("OutboundHttpStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#OutboundXmlTemplate.
        /// </summary>
        public static string OutboundXmlTemplate {
            get {
                return ResourceManager.GetString("OutboundXmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#PropagateFaultMessage.
        /// </summary>
        public static string PropagateFaultMessage {
            get {
                return ResourceManager.GetString("PropagateFaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ProxyAddress.
        /// </summary>
        public static string ProxyAddress {
            get {
                return ResourceManager.GetString("ProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ProxyPassword.
        /// </summary>
        public static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ProxyToUse.
        /// </summary>
        public static string ProxyToUse {
            get {
                return ResourceManager.GetString("ProxyToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ProxyUserName.
        /// </summary>
        public static string ProxyUserName {
            get {
                return ResourceManager.GetString("ProxyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ReferencedBindings.
        /// </summary>
        public static string ReferencedBindings {
            get {
                return ResourceManager.GetString("ReferencedBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ReplyToAddress.
        /// </summary>
        public static string ReplyToAddress {
            get {
                return ResourceManager.GetString("ReplyToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#SecurityMode.
        /// </summary>
        public static string SecurityMode {
            get {
                return ResourceManager.GetString("SecurityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#SendTimeout.
        /// </summary>
        public static string SendTimeout {
            get {
                return ResourceManager.GetString("SendTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ServiceBehaviorConfiguration.
        /// </summary>
        public static string ServiceBehaviorConfiguration {
            get {
                return ResourceManager.GetString("ServiceBehaviorConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#ServiceCertificate.
        /// </summary>
        public static string ServiceCertificate {
            get {
                return ResourceManager.GetString("ServiceCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#SessionIdleTimeout.
        /// </summary>
        public static string SessionIdleTimeout {
            get {
                return ResourceManager.GetString("SessionIdleTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#SharedAccessKey.
        /// </summary>
        public static string SharedAccessKey {
            get {
                return ResourceManager.GetString("SharedAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#SharedAccessKeyName.
        /// </summary>
        public static string SharedAccessKeyName {
            get {
                return ResourceManager.GetString("SharedAccessKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#StsUri.
        /// </summary>
        public static string StsUri {
            get {
                return ResourceManager.GetString("StsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#SuppressMessageBodyForHttpVerbs.
        /// </summary>
        public static string SuppressMessageBodyForHttpVerbs {
            get {
                return ResourceManager.GetString("SuppressMessageBodyForHttpVerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#SuspendMessageOnFailure.
        /// </summary>
        public static string SuspendMessageOnFailure {
            get {
                return ResourceManager.GetString("SuspendMessageOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#TextEncoding.
        /// </summary>
        public static string TextEncoding {
            get {
                return ResourceManager.GetString("TextEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#TimeToLive.
        /// </summary>
        public static string TimeToLive {
            get {
                return ResourceManager.GetString("TimeToLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#TransactionProtocol.
        /// </summary>
        public static string TransactionProtocol {
            get {
                return ResourceManager.GetString("TransactionProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#TransportClientCredentialType.
        /// </summary>
        public static string TransportClientCredentialType {
            get {
                return ResourceManager.GetString("TransportClientCredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#TransportProtectionLevel.
        /// </summary>
        public static string TransportProtectionLevel {
            get {
                return ResourceManager.GetString("TransportProtectionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#UseAcsAuthentication.
        /// </summary>
        public static string UseAcsAuthentication {
            get {
                return ResourceManager.GetString("UseAcsAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#UseSasAuthentication.
        /// </summary>
        public static string UseSasAuthentication {
            get {
                return ResourceManager.GetString("UseSasAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#UseSourceJournal.
        /// </summary>
        public static string UseSourceJournal {
            get {
                return ResourceManager.GetString("UseSourceJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#UseSSO.
        /// </summary>
        public static string UseSSO {
            get {
                return ResourceManager.GetString("UseSSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/01/Adapters/WCF-properties#VariablePropertyMapping.
        /// </summary>
        public static string VariablePropertyMapping {
            get {
                return ResourceManager.GetString("VariablePropertyMapping", resourceCulture);
            }
        }
    }
}
