//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMock.Wcf.Adapter.Utils.BizTalkProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WSS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WSS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransMock.Wcf.Adapter.Utils.BizTalkProperties.WSS", typeof(WSS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigAdapterWSPort.
        /// </summary>
        public static string ConfigAdapterWSPort {
            get {
                return ResourceManager.GetString("ConfigAdapterWSPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigCustomTemplatesDocLib.
        /// </summary>
        public static string ConfigCustomTemplatesDocLib {
            get {
                return ResourceManager.GetString("ConfigCustomTemplatesDocLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigCustomTemplatesNamespaceCol.
        /// </summary>
        public static string ConfigCustomTemplatesNamespaceCol {
            get {
                return ResourceManager.GetString("ConfigCustomTemplatesNamespaceCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigNamespaceAliases.
        /// </summary>
        public static string ConfigNamespaceAliases {
            get {
                return ResourceManager.GetString("ConfigNamespaceAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigOfficeIntegration.
        /// </summary>
        public static string ConfigOfficeIntegration {
            get {
                return ResourceManager.GetString("ConfigOfficeIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigOverwrite.
        /// </summary>
        public static string ConfigOverwrite {
            get {
                return ResourceManager.GetString("ConfigOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigPropertiesXml.
        /// </summary>
        public static string ConfigPropertiesXml {
            get {
                return ResourceManager.GetString("ConfigPropertiesXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigSharePointOnlinePassword.
        /// </summary>
        public static string ConfigSharePointOnlinePassword {
            get {
                return ResourceManager.GetString("ConfigSharePointOnlinePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigSharePointOnlineUsername.
        /// </summary>
        public static string ConfigSharePointOnlineUsername {
            get {
                return ResourceManager.GetString("ConfigSharePointOnlineUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigTemplatesDocLib.
        /// </summary>
        public static string ConfigTemplatesDocLib {
            get {
                return ResourceManager.GetString("ConfigTemplatesDocLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigTemplatesNamespaceCol.
        /// </summary>
        public static string ConfigTemplatesNamespaceCol {
            get {
                return ResourceManager.GetString("ConfigTemplatesNamespaceCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigTimeout.
        /// </summary>
        public static string ConfigTimeout {
            get {
                return ResourceManager.GetString("ConfigTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#ConfigUseClientOM.
        /// </summary>
        public static string ConfigUseClientOM {
            get {
                return ResourceManager.GetString("ConfigUseClientOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InArchivedMsgUrl.
        /// </summary>
        public static string InArchivedMsgUrl {
            get {
                return ResourceManager.GetString("InArchivedMsgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InCreated.
        /// </summary>
        public static string InCreated {
            get {
                return ResourceManager.GetString("InCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InCreatedBy.
        /// </summary>
        public static string InCreatedBy {
            get {
                return ResourceManager.GetString("InCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InEditUrl.
        /// </summary>
        public static string InEditUrl {
            get {
                return ResourceManager.GetString("InEditUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InFileSize.
        /// </summary>
        public static string InFileSize {
            get {
                return ResourceManager.GetString("InFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InIconUrl.
        /// </summary>
        public static string InIconUrl {
            get {
                return ResourceManager.GetString("InIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InItemId.
        /// </summary>
        public static string InItemId {
            get {
                return ResourceManager.GetString("InItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InLastModified.
        /// </summary>
        public static string InLastModified {
            get {
                return ResourceManager.GetString("InLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InLastModifiedBy.
        /// </summary>
        public static string InLastModifiedBy {
            get {
                return ResourceManager.GetString("InLastModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InListName.
        /// </summary>
        public static string InListName {
            get {
                return ResourceManager.GetString("InListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InListUrl.
        /// </summary>
        public static string InListUrl {
            get {
                return ResourceManager.GetString("InListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InOfficeIntegration.
        /// </summary>
        public static string InOfficeIntegration {
            get {
                return ResourceManager.GetString("InOfficeIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InPropertiesXml.
        /// </summary>
        public static string InPropertiesXml {
            get {
                return ResourceManager.GetString("InPropertiesXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#InTitle.
        /// </summary>
        public static string InTitle {
            get {
                return ResourceManager.GetString("InTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties#Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
